// Code generated by "stringer -type=pTYP"; DO NOT EDIT.

package pnml

import "fmt"

const _pTYP_name = "ptDOTptCENUMptFENUMptPRODptNUMERIC"

var _pTYP_index = [...]uint8{0, 5, 12, 19, 25, 34}

func (i TYP) String() string {
	if i < 0 || i >= TYP(len(_pTYP_index)-1) {
		return fmt.Sprintf("pTYP(%d)", i)
	}
	return _pTYP_name[_pTYP_index[i]:_pTYP_index[i+1]]
}
