name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go with version found in the go.mod file
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -v ./pnml ./corenet/
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ubuntu
        path: mcc
